#!/bin/sh

case "$1" in
    start)
        echo "Loading custom ldd modules..."
        modprobe hello
		module_load faulty
		scull_load
        ;;
    stop)
        echo "Unloading custom ldd modules..."
        scull_unload
		module_unload faulty
		modprobe -r hello
        ;;
esac
exit 0
